export default [
  { name: 'Andorra', phoneCode: '376', countryCode: 'AD', chineseName: '安道尔' },
  {
    name: 'United Arab Emirates',
    phoneCode: '971',
    countryCode: 'AE',
    chineseName: '阿拉伯联合酋长国'
  },
  { name: 'Afghanistan', phoneCode: '93', countryCode: 'AF', chineseName: '阿富汗' },
  { name: 'Antigua & Barbuda', phoneCode: '1', countryCode: 'AG', chineseName: '安提瓜和巴布达' },
  { name: 'Anguilla', phoneCode: '1', countryCode: 'AI', chineseName: '安圭拉' },
  { name: 'Albania', phoneCode: '355', countryCode: 'AL', chineseName: '阿尔巴尼亚' },
  { name: 'Armenia', phoneCode: '374', countryCode: 'AM', chineseName: '亚美尼亚' },
  { name: 'Angola', phoneCode: '244', countryCode: 'AO', chineseName: '安哥拉' },
  { name: 'Antarctica', phoneCode: '672', countryCode: 'AQ', chineseName: '南极洲' },
  { name: 'Argentina', phoneCode: '54', countryCode: 'AR', chineseName: '阿根廷' },
  { name: 'American Samoa', phoneCode: '1', countryCode: 'AS', chineseName: '美属萨摩亚' },
  { name: 'Austria', phoneCode: '43', countryCode: 'AT', chineseName: '奥地利' },
  { name: 'Australia', phoneCode: '61', countryCode: 'AU', chineseName: '澳大利亚' },
  { name: 'Aruba', phoneCode: '297', countryCode: 'AW', chineseName: '阿鲁巴' },
  { name: 'Åland Islands', phoneCode: '(null)', countryCode: 'AX', chineseName: '奥兰群岛' },
  { name: 'Azerbaijan', phoneCode: '994', countryCode: 'AZ', chineseName: '阿塞拜疆' },
  {
    name: 'Bosnia & Herzegovina',
    phoneCode: '387',
    countryCode: 'BA',
    chineseName: '波斯尼亚和黑塞哥维那'
  },
  { name: 'Barbados', phoneCode: '1', countryCode: 'BB', chineseName: '巴巴多斯' },
  { name: 'Bangladesh', phoneCode: '880', countryCode: 'BD', chineseName: '孟加拉国' },
  { name: 'Belgium', phoneCode: '32', countryCode: 'BE', chineseName: '比利时' },
  { name: 'Burkina Faso', phoneCode: '226', countryCode: 'BF', chineseName: '布基纳法索' },
  { name: 'Bulgaria', phoneCode: '359', countryCode: 'BG', chineseName: '保加利亚' },
  { name: 'Bahrain', phoneCode: '973', countryCode: 'BH', chineseName: '巴林' },
  { name: 'Burundi', phoneCode: '257', countryCode: 'BI', chineseName: '布隆迪' },
  { name: 'Benin', phoneCode: '229', countryCode: 'BJ', chineseName: '贝宁' },
  { name: 'St. Barthélemy', phoneCode: '590', countryCode: 'BL', chineseName: '圣巴泰勒米' },
  { name: 'Bermuda', phoneCode: '1', countryCode: 'BM', chineseName: '百慕大' },
  { name: 'Brunei', phoneCode: '673', countryCode: 'BN', chineseName: '文莱' },
  { name: 'Bolivia', phoneCode: '591', countryCode: 'BO', chineseName: '玻利维亚' },
  {
    name: 'Caribbean Netherlands',
    phoneCode: '599',
    countryCode: 'BQ',
    chineseName: '荷兰加勒比区'
  },
  { name: 'Brazil', phoneCode: '55', countryCode: 'BR', chineseName: '巴西' },
  { name: 'Bahamas', phoneCode: '1', countryCode: 'BS', chineseName: '巴哈马' },
  { name: 'Bhutan', phoneCode: '975', countryCode: 'BT', chineseName: '不丹' },
  { name: 'Bouvet Island', phoneCode: '(null)', countryCode: 'BV', chineseName: '布维岛' },
  { name: 'Botswana', phoneCode: '267', countryCode: 'BW', chineseName: '博茨瓦纳' },
  { name: 'Belarus', phoneCode: '375', countryCode: 'BY', chineseName: '白俄罗斯' },
  { name: 'Belize', phoneCode: '501', countryCode: 'BZ', chineseName: '伯利兹' },
  { name: 'Canada', phoneCode: '1', countryCode: 'CA', chineseName: '加拿大' },
  {
    name: 'Cocos (Keeling) Islands',
    phoneCode: '61',
    countryCode: 'CC',
    chineseName: '科科斯（基林）群岛'
  },
  { name: 'Congo - Kinshasa', phoneCode: '243', countryCode: 'CD', chineseName: '刚果（金）' },
  {
    name: 'Central African Republic',
    phoneCode: '236',
    countryCode: 'CF',
    chineseName: '中非共和国'
  },
  { name: 'Congo - Brazzaville', phoneCode: '242', countryCode: 'CG', chineseName: '刚果（布）' },
  { name: 'Switzerland', phoneCode: '41', countryCode: 'CH', chineseName: '瑞士' },
  { name: 'Côte d’Ivoire', phoneCode: '225', countryCode: 'CI', chineseName: '科特迪瓦' },
  { name: 'Cook Islands', phoneCode: '682', countryCode: 'CK', chineseName: '库克群岛' },
  { name: 'Chile', phoneCode: '56', countryCode: 'CL', chineseName: '智利' },
  { name: 'Cameroon', phoneCode: '237', countryCode: 'CM', chineseName: '喀麦隆' },
  { name: 'China', phoneCode: '86', countryCode: 'CN', chineseName: '中国' },
  { name: 'Colombia', phoneCode: '57', countryCode: 'CO', chineseName: '哥伦比亚' },
  { name: 'Costa Rica', phoneCode: '506', countryCode: 'CR', chineseName: '哥斯达黎加' },
  { name: 'Cuba', phoneCode: '53', countryCode: 'CU', chineseName: '古巴' },
  { name: 'Cape Verde', phoneCode: '238', countryCode: 'CV', chineseName: '佛得角' },
  { name: 'Curaçao', phoneCode: '5999', countryCode: 'CW', chineseName: '库拉索' },
  { name: 'Christmas Island', phoneCode: '61', countryCode: 'CX', chineseName: '圣诞岛' },
  { name: 'Cyprus', phoneCode: '537', countryCode: 'CY', chineseName: '塞浦路斯' },
  { name: 'Czech Republic', phoneCode: '420', countryCode: 'CZ', chineseName: '捷克共和国' },
  { name: 'Germany', phoneCode: '49', countryCode: 'DE', chineseName: '德国' },
  { name: 'Djibouti', phoneCode: '253', countryCode: 'DJ', chineseName: '吉布提' },
  { name: 'Denmark', phoneCode: '45', countryCode: 'DK', chineseName: '丹麦' },
  { name: 'Dominica', phoneCode: '1', countryCode: 'DM', chineseName: '多米尼克' },
  { name: 'Dominican Republic', phoneCode: '1', countryCode: 'DO', chineseName: '多米尼加共和国' },
  { name: 'Algeria', phoneCode: '213', countryCode: 'DZ', chineseName: '阿尔及利亚' },
  { name: 'Ecuador', phoneCode: '593', countryCode: 'EC', chineseName: '厄瓜多尔' },
  { name: 'Estonia', phoneCode: '372', countryCode: 'EE', chineseName: '爱沙尼亚' },
  { name: 'Egypt', phoneCode: '20', countryCode: 'EG', chineseName: '埃及' },
  { name: 'Western Sahara', phoneCode: '210', countryCode: 'EH', chineseName: '西撒哈拉' },
  { name: 'Eritrea', phoneCode: '291', countryCode: 'ER', chineseName: '厄立特里亚' },
  { name: 'Spain', phoneCode: '34', countryCode: 'ES', chineseName: '西班牙' },
  { name: 'Ethiopia', phoneCode: '251', countryCode: 'ET', chineseName: '埃塞俄比亚' },
  { name: 'Finland', phoneCode: '358', countryCode: 'FI', chineseName: '芬兰' },
  { name: 'Fiji', phoneCode: '679', countryCode: 'FJ', chineseName: '斐济' },
  { name: 'Falkland Islands', phoneCode: '500', countryCode: 'FK', chineseName: '福克兰群岛' },
  { name: 'Micronesia', phoneCode: '691', countryCode: 'FM', chineseName: '密克罗尼西亚' },
  { name: 'Faroe Islands', phoneCode: '298', countryCode: 'FO', chineseName: '法罗群岛' },
  { name: 'France', phoneCode: '33', countryCode: 'FR', chineseName: '法国' },
  { name: 'Gabon', phoneCode: '241', countryCode: 'GA', chineseName: '加蓬' },
  { name: 'United Kingdom', phoneCode: '44', countryCode: 'GB', chineseName: '英国' },
  { name: 'Grenada', phoneCode: '1', countryCode: 'GD', chineseName: '格林纳达' },
  { name: 'Georgia', phoneCode: '995', countryCode: 'GE', chineseName: '格鲁吉亚' },
  { name: 'French Guiana', phoneCode: '594', countryCode: 'GF', chineseName: '法属圭亚那' },
  { name: 'Guernsey', phoneCode: '44', countryCode: 'GG', chineseName: '根西岛' },
  { name: 'Ghana', phoneCode: '233', countryCode: 'GH', chineseName: '加纳' },
  { name: 'Gibraltar', phoneCode: '350', countryCode: 'GI', chineseName: '直布罗陀' },
  { name: 'Greenland', phoneCode: '299', countryCode: 'GL', chineseName: '格陵兰' },
  { name: 'Gambia', phoneCode: '220', countryCode: 'GM', chineseName: '冈比亚' },
  { name: 'Guinea', phoneCode: '224', countryCode: 'GN', chineseName: '几内亚' },
  { name: 'Guadeloupe', phoneCode: '590', countryCode: 'GP', chineseName: '瓜德罗普' },
  { name: 'Equatorial Guinea', phoneCode: '240', countryCode: 'GQ', chineseName: '赤道几内亚' },
  { name: 'Greece', phoneCode: '30', countryCode: 'GR', chineseName: '希腊' },
  {
    name: 'So. Georgia & So. Sandwich Isl.',
    phoneCode: '500',
    countryCode: 'GS',
    chineseName: '南乔治亚岛和南桑威齐群岛'
  },
  { name: 'Guatemala', phoneCode: '502', countryCode: 'GT', chineseName: '危地马拉' },
  { name: 'Guam', phoneCode: '1', countryCode: 'GU', chineseName: '关岛' },
  { name: 'Guinea-Bissau', phoneCode: '245', countryCode: 'GW', chineseName: '几内亚比绍' },
  { name: 'Guyana', phoneCode: '595', countryCode: 'GY', chineseName: '圭亚那' },
  {
    name: 'Hong Kong SAR China',
    phoneCode: '852',
    countryCode: 'HK',
    chineseName: '中国香港特别行政区'
  },
  {
    name: 'Heard & McDonald Islands',
    phoneCode: '(null)',
    countryCode: 'HM',
    chineseName: '赫德岛和麦克唐纳群岛'
  },
  { name: 'Honduras', phoneCode: '504', countryCode: 'HN', chineseName: '洪都拉斯' },
  { name: 'Croatia', phoneCode: '385', countryCode: 'HR', chineseName: '克罗地亚' },
  { name: 'Haiti', phoneCode: '509', countryCode: 'HT', chineseName: '海地' },
  { name: 'Hungary', phoneCode: '36', countryCode: 'HU', chineseName: '匈牙利' },
  { name: 'Indonesia', phoneCode: '62', countryCode: 'ID', chineseName: '印度尼西亚' },
  { name: 'Ireland', phoneCode: '353', countryCode: 'IE', chineseName: '爱尔兰' },
  { name: 'Israel', phoneCode: '972', countryCode: 'IL', chineseName: '以色列' },
  { name: 'Isle of Man', phoneCode: '44', countryCode: 'IM', chineseName: '曼岛' },
  { name: 'India', phoneCode: '91', countryCode: 'IN', chineseName: '印度' },
  {
    name: 'British Indian Ocean Territory',
    phoneCode: '246',
    countryCode: 'IO',
    chineseName: '英属印度洋领地'
  },
  { name: 'Iraq', phoneCode: '964', countryCode: 'IQ', chineseName: '伊拉克' },
  { name: 'Iran', phoneCode: '98', countryCode: 'IR', chineseName: '伊朗' },
  { name: 'Iceland', phoneCode: '354', countryCode: 'IS', chineseName: '冰岛' },
  { name: 'Italy', phoneCode: '39', countryCode: 'IT', chineseName: '意大利' },
  { name: 'Jersey', phoneCode: '44', countryCode: 'JE', chineseName: '泽西岛' },
  { name: 'Jamaica', phoneCode: '1', countryCode: 'JM', chineseName: '牙买加' },
  { name: 'Jordan', phoneCode: '962', countryCode: 'JO', chineseName: '约旦' },
  { name: 'Japan', phoneCode: '81', countryCode: 'JP', chineseName: '日本' },
  { name: 'Kenya', phoneCode: '254', countryCode: 'KE', chineseName: '肯尼亚' },
  { name: 'Kyrgyzstan', phoneCode: '996', countryCode: 'KG', chineseName: '吉尔吉斯斯坦' },
  { name: 'Cambodia', phoneCode: '855', countryCode: 'KH', chineseName: '柬埔寨' },
  { name: 'Kiribati', phoneCode: '686', countryCode: 'KI', chineseName: '基里巴斯' },
  { name: 'Comoros', phoneCode: '269', countryCode: 'KM', chineseName: '科摩罗' },
  { name: 'St. Kitts & Nevis', phoneCode: '1', countryCode: 'KN', chineseName: '圣基茨和尼维斯' },
  { name: 'North Korea', phoneCode: '850', countryCode: 'KP', chineseName: '朝鲜' },
  { name: 'South Korea', phoneCode: '82', countryCode: 'KR', chineseName: '韩国' },
  { name: 'Kuwait', phoneCode: '965', countryCode: 'KW', chineseName: '科威特' },
  { name: 'Cayman Islands', phoneCode: '345', countryCode: 'KY', chineseName: '开曼群岛' },
  { name: 'Kazakhstan', phoneCode: '77', countryCode: 'KZ', chineseName: '哈萨克斯坦' },
  { name: 'Laos', phoneCode: '856', countryCode: 'LA', chineseName: '老挝' },
  { name: 'Lebanon', phoneCode: '961', countryCode: 'LB', chineseName: '黎巴嫩' },
  { name: 'St. Lucia', phoneCode: '1', countryCode: 'LC', chineseName: '圣卢西亚' },
  { name: 'Liechtenstein', phoneCode: '423', countryCode: 'LI', chineseName: '列支敦士登' },
  { name: 'Sri Lanka', phoneCode: '94', countryCode: 'LK', chineseName: '斯里兰卡' },
  { name: 'Liberia', phoneCode: '231', countryCode: 'LR', chineseName: '利比里亚' },
  { name: 'Lesotho', phoneCode: '266', countryCode: 'LS', chineseName: '莱索托' },
  { name: 'Lithuania', phoneCode: '370', countryCode: 'LT', chineseName: '立陶宛' },
  { name: 'Luxembourg', phoneCode: '352', countryCode: 'LU', chineseName: '卢森堡' },
  { name: 'Latvia', phoneCode: '371', countryCode: 'LV', chineseName: '拉脱维亚' },
  { name: 'Libya', phoneCode: '218', countryCode: 'LY', chineseName: '利比亚' },
  { name: 'Morocco', phoneCode: '212', countryCode: 'MA', chineseName: '摩洛哥' },
  { name: 'Monaco', phoneCode: '377', countryCode: 'MC', chineseName: '摩纳哥' },
  { name: 'Moldova', phoneCode: '373', countryCode: 'MD', chineseName: '摩尔多瓦' },
  { name: 'Montenegro', phoneCode: '382', countryCode: 'ME', chineseName: '黑山' },
  { name: 'St. Martin', phoneCode: '590', countryCode: 'MF', chineseName: '法属圣马丁' },
  { name: 'Madagascar', phoneCode: '261', countryCode: 'MG', chineseName: '马达加斯加' },
  { name: 'Marshall Islands', phoneCode: '692', countryCode: 'MH', chineseName: '马绍尔群岛' },
  { name: 'Macedonia', phoneCode: '389', countryCode: 'MK', chineseName: '马其顿' },
  { name: 'Mali', phoneCode: '223', countryCode: 'ML', chineseName: '马里' },
  { name: 'Myanmar (Burma)', phoneCode: '95', countryCode: 'MM', chineseName: '缅甸' },
  { name: 'Mongolia', phoneCode: '976', countryCode: 'MN', chineseName: '蒙古' },
  {
    name: 'Macau SAR China',
    phoneCode: '853',
    countryCode: 'MO',
    chineseName: '中国澳门特别行政区'
  },
  {
    name: 'Northern Mariana Islands',
    phoneCode: '1',
    countryCode: 'MP',
    chineseName: '北马里亚纳群岛'
  },
  { name: 'Martinique', phoneCode: '596', countryCode: 'MQ', chineseName: '马提尼克' },
  { name: 'Mauritania', phoneCode: '222', countryCode: 'MR', chineseName: '毛里塔尼亚' },
  { name: 'Montserrat', phoneCode: '1', countryCode: 'MS', chineseName: '蒙特塞拉特' },
  { name: 'Malta', phoneCode: '356', countryCode: 'MT', chineseName: '马耳他' },
  { name: 'Mauritius', phoneCode: '230', countryCode: 'MU', chineseName: '毛里求斯' },
  { name: 'Maldives', phoneCode: '960', countryCode: 'MV', chineseName: '马尔代夫' },
  { name: 'Malawi', phoneCode: '265', countryCode: 'MW', chineseName: '马拉维' },
  { name: 'Mexico', phoneCode: '52', countryCode: 'MX', chineseName: '墨西哥' },
  { name: 'Malaysia', phoneCode: '60', countryCode: 'MY', chineseName: '马来西亚' },
  { name: 'Mozambique', phoneCode: '258', countryCode: 'MZ', chineseName: '莫桑比克' },
  { name: 'Namibia', phoneCode: '264', countryCode: 'NA', chineseName: '纳米比亚' },
  { name: 'New Caledonia', phoneCode: '687', countryCode: 'NC', chineseName: '新喀里多尼亚' },
  { name: 'Niger', phoneCode: '227', countryCode: 'NE', chineseName: '尼日尔' },
  { name: 'Norfolk Island', phoneCode: '672', countryCode: 'NF', chineseName: '诺福克岛' },
  { name: 'Nigeria', phoneCode: '234', countryCode: 'NG', chineseName: '尼日利亚' },
  { name: 'Nicaragua', phoneCode: '505', countryCode: 'NI', chineseName: '尼加拉瓜' },
  { name: 'Netherlands', phoneCode: '31', countryCode: 'NL', chineseName: '荷兰' },
  { name: 'Norway', phoneCode: '47', countryCode: 'NO', chineseName: '挪威' },
  { name: 'Nepal', phoneCode: '977', countryCode: 'NP', chineseName: '尼泊尔' },
  { name: 'Nauru', phoneCode: '674', countryCode: 'NR', chineseName: '瑙鲁' },
  { name: 'Niue', phoneCode: '683', countryCode: 'NU', chineseName: '纽埃' },
  { name: 'New Zealand', phoneCode: '64', countryCode: 'NZ', chineseName: '新西兰' },
  { name: 'Oman', phoneCode: '968', countryCode: 'OM', chineseName: '阿曼' },
  { name: 'Panama', phoneCode: '507', countryCode: 'PA', chineseName: '巴拿马' },
  { name: 'Peru', phoneCode: '51', countryCode: 'PE', chineseName: '秘鲁' },
  { name: 'French Polynesia', phoneCode: '689', countryCode: 'PF', chineseName: '法属波利尼西亚' },
  { name: 'Papua New Guinea', phoneCode: '675', countryCode: 'PG', chineseName: '巴布亚新几内亚' },
  { name: 'Philippines', phoneCode: '63', countryCode: 'PH', chineseName: '菲律宾' },
  { name: 'Pakistan', phoneCode: '92', countryCode: 'PK', chineseName: '巴基斯坦' },
  { name: 'Poland', phoneCode: '48', countryCode: 'PL', chineseName: '波兰' },
  {
    name: 'St. Pierre & Miquelon',
    phoneCode: '508',
    countryCode: 'PM',
    chineseName: '圣皮埃尔和密克隆群岛'
  },
  { name: 'Pitcairn Islands', phoneCode: '872', countryCode: 'PN', chineseName: '皮特凯恩群岛' },
  { name: 'Puerto Rico', phoneCode: '1', countryCode: 'PR', chineseName: '波多黎各' },
  {
    name: 'Palestinian Territories',
    phoneCode: '970',
    countryCode: 'PS',
    chineseName: '巴勒斯坦领土'
  },
  { name: 'Portugal', phoneCode: '351', countryCode: 'PT', chineseName: '葡萄牙' },
  { name: 'Palau', phoneCode: '680', countryCode: 'PW', chineseName: '帕劳' },
  { name: 'Paraguay', phoneCode: '595', countryCode: 'PY', chineseName: '巴拉圭' },
  { name: 'Qatar', phoneCode: '974', countryCode: 'QA', chineseName: '卡塔尔' },
  { name: 'Réunion', phoneCode: '262', countryCode: 'RE', chineseName: '留尼汪' },
  { name: 'Romania', phoneCode: '40', countryCode: 'RO', chineseName: '罗马尼亚' },
  { name: 'Serbia', phoneCode: '381', countryCode: 'RS', chineseName: '塞尔维亚' },
  { name: 'Russia', phoneCode: '7', countryCode: 'RU', chineseName: '俄罗斯' },
  { name: 'Rwanda', phoneCode: '250', countryCode: 'RW', chineseName: '卢旺达' },
  { name: 'Saudi Arabia', phoneCode: '966', countryCode: 'SA', chineseName: '沙特阿拉伯' },
  { name: 'Solomon Islands', phoneCode: '677', countryCode: 'SB', chineseName: '所罗门群岛' },
  { name: 'Seychelles', phoneCode: '248', countryCode: 'SC', chineseName: '塞舌尔' },
  { name: 'Sudan', phoneCode: '249', countryCode: 'SD', chineseName: '苏丹' },
  { name: 'Sweden', phoneCode: '46', countryCode: 'SE', chineseName: '瑞典' },
  { name: 'Singapore', phoneCode: '65', countryCode: 'SG', chineseName: '新加坡' },
  { name: 'St. Helena', phoneCode: '290', countryCode: 'SH', chineseName: '圣赫勒拿' },
  { name: 'Slovenia', phoneCode: '386', countryCode: 'SI', chineseName: '斯洛文尼亚' },
  {
    name: 'Svalbard & Jan Mayen',
    phoneCode: '47',
    countryCode: 'SJ',
    chineseName: '斯瓦尔巴特和扬马延'
  },
  { name: 'Slovakia', phoneCode: '421', countryCode: 'SK', chineseName: '斯洛伐克' },
  { name: 'Sierra Leone', phoneCode: '232', countryCode: 'SL', chineseName: '塞拉利昂' },
  { name: 'San Marino', phoneCode: '378', countryCode: 'SM', chineseName: '圣马力诺' },
  { name: 'Senegal', phoneCode: '221', countryCode: 'SN', chineseName: '塞内加尔' },
  { name: 'Somalia', phoneCode: '252', countryCode: 'SO', chineseName: '索马里' },
  { name: 'Suriname', phoneCode: '597', countryCode: 'SR', chineseName: '苏里南' },
  { name: 'South Sudan', phoneCode: '211', countryCode: 'SS', chineseName: '南苏丹' },
  {
    name: 'São Tomé & Príncipe',
    phoneCode: '239',
    countryCode: 'ST',
    chineseName: '圣多美和普林西比'
  },
  { name: 'El Salvador', phoneCode: '503', countryCode: 'SV', chineseName: '萨尔瓦多' },
  { name: 'Sint Maarten', phoneCode: '599', countryCode: 'SX', chineseName: '荷属圣马丁' },
  { name: 'Syria', phoneCode: '963', countryCode: 'SY', chineseName: '叙利亚' },
  { name: 'Swaziland', phoneCode: '268', countryCode: 'SZ', chineseName: '斯威士兰' },
  {
    name: 'Turks & Caicos Islands',
    phoneCode: '1',
    countryCode: 'TC',
    chineseName: '特克斯和凯科斯群岛'
  },
  { name: 'Chad', phoneCode: '235', countryCode: 'TD', chineseName: '乍得' },
  {
    name: 'French Southern Territories',
    phoneCode: '(null)',
    countryCode: 'TF',
    chineseName: '法属南部领地'
  },
  { name: 'Togo', phoneCode: '228', countryCode: 'TG', chineseName: '多哥' },
  { name: 'Thailand', phoneCode: '66', countryCode: 'TH', chineseName: '泰国' },
  { name: 'Tajikistan', phoneCode: '992', countryCode: 'TJ', chineseName: '塔吉克斯坦' },
  { name: 'Tokelau', phoneCode: '690', countryCode: 'TK', chineseName: '托克劳' },
  { name: 'Timor-Leste', phoneCode: '670', countryCode: 'TL', chineseName: '东帝汶' },
  { name: 'Turkmenistan', phoneCode: '993', countryCode: 'TM', chineseName: '土库曼斯坦' },
  { name: 'Tunisia', phoneCode: '216', countryCode: 'TN', chineseName: '突尼斯' },
  { name: 'Tonga', phoneCode: '676', countryCode: 'TO', chineseName: '汤加' },
  { name: 'Turkey', phoneCode: '90', countryCode: 'TR', chineseName: '土耳其' },
  { name: 'Trinidad & Tobago', phoneCode: '1', countryCode: 'TT', chineseName: '特立尼达和多巴哥' },
  { name: 'Tuvalu', phoneCode: '688', countryCode: 'TV', chineseName: '图瓦卢' },
  { name: 'Taiwan', phoneCode: '886', countryCode: 'TW', chineseName: '台湾' },
  { name: 'Tanzania', phoneCode: '255', countryCode: 'TZ', chineseName: '坦桑尼亚' },
  { name: 'Ukraine', phoneCode: '380', countryCode: 'UA', chineseName: '乌克兰' },
  { name: 'Uganda', phoneCode: '256', countryCode: 'UG', chineseName: '乌干达' },
  {
    name: 'U.S. Outlying Islands',
    phoneCode: '(null)',
    countryCode: 'UM',
    chineseName: '美国本土外小岛屿'
  },
  { name: 'United States', phoneCode: '1', countryCode: 'US', chineseName: '美国' },
  { name: 'Uruguay', phoneCode: '598', countryCode: 'UY', chineseName: '乌拉圭' },
  { name: 'Uzbekistan', phoneCode: '998', countryCode: 'UZ', chineseName: '乌兹别克斯坦' },
  { name: 'Vatican City', phoneCode: '379', countryCode: 'VA', chineseName: '梵蒂冈' },
  {
    name: 'St. Vincent & Grenadines',
    phoneCode: '1',
    countryCode: 'VC',
    chineseName: '圣文森特和格林纳丁斯'
  },
  { name: 'Venezuela', phoneCode: '58', countryCode: 'VE', chineseName: '委内瑞拉' },
  {
    name: 'British Virgin Islands',
    phoneCode: '1',
    countryCode: 'VG',
    chineseName: '英属维京群岛'
  },
  { name: 'U.S. Virgin Islands', phoneCode: '1', countryCode: 'VI', chineseName: '美属维京群岛' },
  { name: 'Vietnam', phoneCode: '84', countryCode: 'VN', chineseName: '越南' },
  { name: 'Vanuatu', phoneCode: '678', countryCode: 'VU', chineseName: '瓦努阿图' },
  { name: 'Wallis & Futuna', phoneCode: '681', countryCode: 'WF', chineseName: '瓦利斯和富图纳' },
  { name: 'Samoa', phoneCode: '685', countryCode: 'WS', chineseName: '萨摩亚' },
  { name: 'Yemen', phoneCode: '967', countryCode: 'YE', chineseName: '也门' },
  { name: 'Mayotte', phoneCode: '262', countryCode: 'YT', chineseName: '马约特' },
  { name: 'South Africa', phoneCode: '27', countryCode: 'ZA', chineseName: '南非' },
  { name: 'Zambia', phoneCode: '260', countryCode: 'ZM', chineseName: '赞比亚' },
  { name: 'Zimbabwe', phoneCode: '263', countryCode: 'ZW', chineseName: '津巴布韦' }
];
