export default [
  { name: 'Andorra', code: 'AD', phoneCode: '376', chineseName: '安道尔' },
  { name: 'United Arab Emirates', code: 'AE', phoneCode: '971', chineseName: '阿拉伯联合酋长国' },
  { name: 'Afghanistan', code: 'AF', phoneCode: '93', chineseName: '阿富汗' },
  { name: 'Antigua & Barbuda', code: 'AG', phoneCode: '1', chineseName: '安提瓜和巴布达' },
  { name: 'Anguilla', code: 'AI', phoneCode: '1', chineseName: '安圭拉' },
  { name: 'Albania', code: 'AL', phoneCode: '355', chineseName: '阿尔巴尼亚' },
  { name: 'Armenia', code: 'AM', phoneCode: '374', chineseName: '亚美尼亚' },
  { name: 'Angola', code: 'AO', phoneCode: '244', chineseName: '安哥拉' },
  { name: 'Antarctica', code: 'AQ', phoneCode: '672', chineseName: '南极洲' },
  { name: 'Argentina', code: 'AR', phoneCode: '54', chineseName: '阿根廷' },
  { name: 'American Samoa', code: 'AS', phoneCode: '1', chineseName: '美属萨摩亚' },
  { name: 'Austria', code: 'AT', phoneCode: '43', chineseName: '奥地利' },
  { name: 'Australia', code: 'AU', phoneCode: '61', chineseName: '澳大利亚' },
  { name: 'Aruba', code: 'AW', phoneCode: '297', chineseName: '阿鲁巴' },
  { name: 'Åland Islands', code: 'AX', phoneCode: '(null)', chineseName: '奥兰群岛' },
  { name: 'Azerbaijan', code: 'AZ', phoneCode: '994', chineseName: '阿塞拜疆' },
  {
    name: 'Bosnia & Herzegovina',
    code: 'BA',
    phoneCode: '387',
    chineseName: '波斯尼亚和黑塞哥维那'
  },
  { name: 'Barbados', code: 'BB', phoneCode: '1', chineseName: '巴巴多斯' },
  { name: 'Bangladesh', code: 'BD', phoneCode: '880', chineseName: '孟加拉国' },
  { name: 'Belgium', code: 'BE', phoneCode: '32', chineseName: '比利时' },
  { name: 'Burkina Faso', code: 'BF', phoneCode: '226', chineseName: '布基纳法索' },
  { name: 'Bulgaria', code: 'BG', phoneCode: '359', chineseName: '保加利亚' },
  { name: 'Bahrain', code: 'BH', phoneCode: '973', chineseName: '巴林' },
  { name: 'Burundi', code: 'BI', phoneCode: '257', chineseName: '布隆迪' },
  { name: 'Benin', code: 'BJ', phoneCode: '229', chineseName: '贝宁' },
  { name: 'St. Barthélemy', code: 'BL', phoneCode: '590', chineseName: '圣巴泰勒米' },
  { name: 'Bermuda', code: 'BM', phoneCode: '1', chineseName: '百慕大' },
  { name: 'Brunei', code: 'BN', phoneCode: '673', chineseName: '文莱' },
  { name: 'Bolivia', code: 'BO', phoneCode: '591', chineseName: '玻利维亚' },
  { name: 'Caribbean Netherlands', code: 'BQ', phoneCode: '599', chineseName: '荷兰加勒比区' },
  { name: 'Brazil', code: 'BR', phoneCode: '55', chineseName: '巴西' },
  { name: 'Bahamas', code: 'BS', phoneCode: '1', chineseName: '巴哈马' },
  { name: 'Bhutan', code: 'BT', phoneCode: '975', chineseName: '不丹' },
  { name: 'Bouvet Island', code: 'BV', phoneCode: '(null)', chineseName: '布维岛' },
  { name: 'Botswana', code: 'BW', phoneCode: '267', chineseName: '博茨瓦纳' },
  { name: 'Belarus', code: 'BY', phoneCode: '375', chineseName: '白俄罗斯' },
  { name: 'Belize', code: 'BZ', phoneCode: '501', chineseName: '伯利兹' },
  { name: 'Canada', code: 'CA', phoneCode: '1', chineseName: '加拿大' },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    phoneCode: '61',
    chineseName: '科科斯（基林）群岛'
  },
  { name: 'Congo - Kinshasa', code: 'CD', phoneCode: '243', chineseName: '刚果（金）' },
  { name: 'Central African Republic', code: 'CF', phoneCode: '236', chineseName: '中非共和国' },
  { name: 'Congo - Brazzaville', code: 'CG', phoneCode: '242', chineseName: '刚果（布）' },
  { name: 'Switzerland', code: 'CH', phoneCode: '41', chineseName: '瑞士' },
  { name: 'Côte d’Ivoire', code: 'CI', phoneCode: '225', chineseName: '科特迪瓦' },
  { name: 'Cook Islands', code: 'CK', phoneCode: '682', chineseName: '库克群岛' },
  { name: 'Chile', code: 'CL', phoneCode: '56', chineseName: '智利' },
  { name: 'Cameroon', code: 'CM', phoneCode: '237', chineseName: '喀麦隆' },
  { name: 'China', code: 'CN', phoneCode: '86', chineseName: '中国' },
  { name: 'Colombia', code: 'CO', phoneCode: '57', chineseName: '哥伦比亚' },
  { name: 'Costa Rica', code: 'CR', phoneCode: '506', chineseName: '哥斯达黎加' },
  { name: 'Cuba', code: 'CU', phoneCode: '53', chineseName: '古巴' },
  { name: 'Cape Verde', code: 'CV', phoneCode: '238', chineseName: '佛得角' },
  { name: 'Curaçao', code: 'CW', phoneCode: '5999', chineseName: '库拉索' },
  { name: 'Christmas Island', code: 'CX', phoneCode: '61', chineseName: '圣诞岛' },
  { name: 'Cyprus', code: 'CY', phoneCode: '537', chineseName: '塞浦路斯' },
  { name: 'Czech Republic', code: 'CZ', phoneCode: '420', chineseName: '捷克共和国' },
  { name: 'Germany', code: 'DE', phoneCode: '49', chineseName: '德国' },
  { name: 'Djibouti', code: 'DJ', phoneCode: '253', chineseName: '吉布提' },
  { name: 'Denmark', code: 'DK', phoneCode: '45', chineseName: '丹麦' },
  { name: 'Dominica', code: 'DM', phoneCode: '1', chineseName: '多米尼克' },
  { name: 'Dominican Republic', code: 'DO', phoneCode: '1', chineseName: '多米尼加共和国' },
  { name: 'Algeria', code: 'DZ', phoneCode: '213', chineseName: '阿尔及利亚' },
  { name: 'Ecuador', code: 'EC', phoneCode: '593', chineseName: '厄瓜多尔' },
  { name: 'Estonia', code: 'EE', phoneCode: '372', chineseName: '爱沙尼亚' },
  { name: 'Egypt', code: 'EG', phoneCode: '20', chineseName: '埃及' },
  { name: 'Western Sahara', code: 'EH', phoneCode: '210', chineseName: '西撒哈拉' },
  { name: 'Eritrea', code: 'ER', phoneCode: '291', chineseName: '厄立特里亚' },
  { name: 'Spain', code: 'ES', phoneCode: '34', chineseName: '西班牙' },
  { name: 'Ethiopia', code: 'ET', phoneCode: '251', chineseName: '埃塞俄比亚' },
  { name: 'Finland', code: 'FI', phoneCode: '358', chineseName: '芬兰' },
  { name: 'Fiji', code: 'FJ', phoneCode: '679', chineseName: '斐济' },
  { name: 'Falkland Islands', code: 'FK', phoneCode: '500', chineseName: '福克兰群岛' },
  { name: 'Micronesia', code: 'FM', phoneCode: '691', chineseName: '密克罗尼西亚' },
  { name: 'Faroe Islands', code: 'FO', phoneCode: '298', chineseName: '法罗群岛' },
  { name: 'France', code: 'FR', phoneCode: '33', chineseName: '法国' },
  { name: 'Gabon', code: 'GA', phoneCode: '241', chineseName: '加蓬' },
  { name: 'United Kingdom', code: 'GB', phoneCode: '44', chineseName: '英国' },
  { name: 'Grenada', code: 'GD', phoneCode: '1', chineseName: '格林纳达' },
  { name: 'Georgia', code: 'GE', phoneCode: '995', chineseName: '格鲁吉亚' },
  { name: 'French Guiana', code: 'GF', phoneCode: '594', chineseName: '法属圭亚那' },
  { name: 'Guernsey', code: 'GG', phoneCode: '44', chineseName: '根西岛' },
  { name: 'Ghana', code: 'GH', phoneCode: '233', chineseName: '加纳' },
  { name: 'Gibraltar', code: 'GI', phoneCode: '350', chineseName: '直布罗陀' },
  { name: 'Greenland', code: 'GL', phoneCode: '299', chineseName: '格陵兰' },
  { name: 'Gambia', code: 'GM', phoneCode: '220', chineseName: '冈比亚' },
  { name: 'Guinea', code: 'GN', phoneCode: '224', chineseName: '几内亚' },
  { name: 'Guadeloupe', code: 'GP', phoneCode: '590', chineseName: '瓜德罗普' },
  { name: 'Equatorial Guinea', code: 'GQ', phoneCode: '240', chineseName: '赤道几内亚' },
  { name: 'Greece', code: 'GR', phoneCode: '30', chineseName: '希腊' },
  {
    name: 'So. Georgia & So. Sandwich Isl.',
    code: 'GS',
    phoneCode: '500',
    chineseName: '南乔治亚岛和南桑威齐群岛'
  },
  { name: 'Guatemala', code: 'GT', phoneCode: '502', chineseName: '危地马拉' },
  { name: 'Guam', code: 'GU', phoneCode: '1', chineseName: '关岛' },
  { name: 'Guinea-Bissau', code: 'GW', phoneCode: '245', chineseName: '几内亚比绍' },
  { name: 'Guyana', code: 'GY', phoneCode: '595', chineseName: '圭亚那' },
  { name: 'Hong Kong SAR China', code: 'HK', phoneCode: '852', chineseName: '中国香港特别行政区' },
  {
    name: 'Heard & McDonald Islands',
    code: 'HM',
    phoneCode: '(null)',
    chineseName: '赫德岛和麦克唐纳群岛'
  },
  { name: 'Honduras', code: 'HN', phoneCode: '504', chineseName: '洪都拉斯' },
  { name: 'Croatia', code: 'HR', phoneCode: '385', chineseName: '克罗地亚' },
  { name: 'Haiti', code: 'HT', phoneCode: '509', chineseName: '海地' },
  { name: 'Hungary', code: 'HU', phoneCode: '36', chineseName: '匈牙利' },
  { name: 'Indonesia', code: 'ID', phoneCode: '62', chineseName: '印度尼西亚' },
  { name: 'Ireland', code: 'IE', phoneCode: '353', chineseName: '爱尔兰' },
  { name: 'Israel', code: 'IL', phoneCode: '972', chineseName: '以色列' },
  { name: 'Isle of Man', code: 'IM', phoneCode: '44', chineseName: '曼岛' },
  { name: 'India', code: 'IN', phoneCode: '91', chineseName: '印度' },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    phoneCode: '246',
    chineseName: '英属印度洋领地'
  },
  { name: 'Iraq', code: 'IQ', phoneCode: '964', chineseName: '伊拉克' },
  { name: 'Iran', code: 'IR', phoneCode: '98', chineseName: '伊朗' },
  { name: 'Iceland', code: 'IS', phoneCode: '354', chineseName: '冰岛' },
  { name: 'Italy', code: 'IT', phoneCode: '39', chineseName: '意大利' },
  { name: 'Jersey', code: 'JE', phoneCode: '44', chineseName: '泽西岛' },
  { name: 'Jamaica', code: 'JM', phoneCode: '1', chineseName: '牙买加' },
  { name: 'Jordan', code: 'JO', phoneCode: '962', chineseName: '约旦' },
  { name: 'Japan', code: 'JP', phoneCode: '81', chineseName: '日本' },
  { name: 'Kenya', code: 'KE', phoneCode: '254', chineseName: '肯尼亚' },
  { name: 'Kyrgyzstan', code: 'KG', phoneCode: '996', chineseName: '吉尔吉斯斯坦' },
  { name: 'Cambodia', code: 'KH', phoneCode: '855', chineseName: '柬埔寨' },
  { name: 'Kiribati', code: 'KI', phoneCode: '686', chineseName: '基里巴斯' },
  { name: 'Comoros', code: 'KM', phoneCode: '269', chineseName: '科摩罗' },
  { name: 'St. Kitts & Nevis', code: 'KN', phoneCode: '1', chineseName: '圣基茨和尼维斯' },
  { name: 'North Korea', code: 'KP', phoneCode: '850', chineseName: '朝鲜' },
  { name: 'South Korea', code: 'KR', phoneCode: '82', chineseName: '韩国' },
  { name: 'Kuwait', code: 'KW', phoneCode: '965', chineseName: '科威特' },
  { name: 'Cayman Islands', code: 'KY', phoneCode: '345', chineseName: '开曼群岛' },
  { name: 'Kazakhstan', code: 'KZ', phoneCode: '77', chineseName: '哈萨克斯坦' },
  { name: 'Laos', code: 'LA', phoneCode: '856', chineseName: '老挝' },
  { name: 'Lebanon', code: 'LB', phoneCode: '961', chineseName: '黎巴嫩' },
  { name: 'St. Lucia', code: 'LC', phoneCode: '1', chineseName: '圣卢西亚' },
  { name: 'Liechtenstein', code: 'LI', phoneCode: '423', chineseName: '列支敦士登' },
  { name: 'Sri Lanka', code: 'LK', phoneCode: '94', chineseName: '斯里兰卡' },
  { name: 'Liberia', code: 'LR', phoneCode: '231', chineseName: '利比里亚' },
  { name: 'Lesotho', code: 'LS', phoneCode: '266', chineseName: '莱索托' },
  { name: 'Lithuania', code: 'LT', phoneCode: '370', chineseName: '立陶宛' },
  { name: 'Luxembourg', code: 'LU', phoneCode: '352', chineseName: '卢森堡' },
  { name: 'Latvia', code: 'LV', phoneCode: '371', chineseName: '拉脱维亚' },
  { name: 'Libya', code: 'LY', phoneCode: '218', chineseName: '利比亚' },
  { name: 'Morocco', code: 'MA', phoneCode: '212', chineseName: '摩洛哥' },
  { name: 'Monaco', code: 'MC', phoneCode: '377', chineseName: '摩纳哥' },
  { name: 'Moldova', code: 'MD', phoneCode: '373', chineseName: '摩尔多瓦' },
  { name: 'Montenegro', code: 'ME', phoneCode: '382', chineseName: '黑山' },
  { name: 'St. Martin', code: 'MF', phoneCode: '590', chineseName: '法属圣马丁' },
  { name: 'Madagascar', code: 'MG', phoneCode: '261', chineseName: '马达加斯加' },
  { name: 'Marshall Islands', code: 'MH', phoneCode: '692', chineseName: '马绍尔群岛' },
  { name: 'Macedonia', code: 'MK', phoneCode: '389', chineseName: '马其顿' },
  { name: 'Mali', code: 'ML', phoneCode: '223', chineseName: '马里' },
  { name: 'Myanmar (Burma)', code: 'MM', phoneCode: '95', chineseName: '缅甸' },
  { name: 'Mongolia', code: 'MN', phoneCode: '976', chineseName: '蒙古' },
  { name: 'Macau SAR China', code: 'MO', phoneCode: '853', chineseName: '中国澳门特别行政区' },
  { name: 'Northern Mariana Islands', code: 'MP', phoneCode: '1', chineseName: '北马里亚纳群岛' },
  { name: 'Martinique', code: 'MQ', phoneCode: '596', chineseName: '马提尼克' },
  { name: 'Mauritania', code: 'MR', phoneCode: '222', chineseName: '毛里塔尼亚' },
  { name: 'Montserrat', code: 'MS', phoneCode: '1', chineseName: '蒙特塞拉特' },
  { name: 'Malta', code: 'MT', phoneCode: '356', chineseName: '马耳他' },
  { name: 'Mauritius', code: 'MU', phoneCode: '230', chineseName: '毛里求斯' },
  { name: 'Maldives', code: 'MV', phoneCode: '960', chineseName: '马尔代夫' },
  { name: 'Malawi', code: 'MW', phoneCode: '265', chineseName: '马拉维' },
  { name: 'Mexico', code: 'MX', phoneCode: '52', chineseName: '墨西哥' },
  { name: 'Malaysia', code: 'MY', phoneCode: '60', chineseName: '马来西亚' },
  { name: 'Mozambique', code: 'MZ', phoneCode: '258', chineseName: '莫桑比克' },
  { name: 'Namibia', code: 'NA', phoneCode: '264', chineseName: '纳米比亚' },
  { name: 'New Caledonia', code: 'NC', phoneCode: '687', chineseName: '新喀里多尼亚' },
  { name: 'Niger', code: 'NE', phoneCode: '227', chineseName: '尼日尔' },
  { name: 'Norfolk Island', code: 'NF', phoneCode: '672', chineseName: '诺福克岛' },
  { name: 'Nigeria', code: 'NG', phoneCode: '234', chineseName: '尼日利亚' },
  { name: 'Nicaragua', code: 'NI', phoneCode: '505', chineseName: '尼加拉瓜' },
  { name: 'Netherlands', code: 'NL', phoneCode: '31', chineseName: '荷兰' },
  { name: 'Norway', code: 'NO', phoneCode: '47', chineseName: '挪威' },
  { name: 'Nepal', code: 'NP', phoneCode: '977', chineseName: '尼泊尔' },
  { name: 'Nauru', code: 'NR', phoneCode: '674', chineseName: '瑙鲁' },
  { name: 'Niue', code: 'NU', phoneCode: '683', chineseName: '纽埃' },
  { name: 'New Zealand', code: 'NZ', phoneCode: '64', chineseName: '新西兰' },
  { name: 'Oman', code: 'OM', phoneCode: '968', chineseName: '阿曼' },
  { name: 'Panama', code: 'PA', phoneCode: '507', chineseName: '巴拿马' },
  { name: 'Peru', code: 'PE', phoneCode: '51', chineseName: '秘鲁' },
  { name: 'French Polynesia', code: 'PF', phoneCode: '689', chineseName: '法属波利尼西亚' },
  { name: 'Papua New Guinea', code: 'PG', phoneCode: '675', chineseName: '巴布亚新几内亚' },
  { name: 'Philippines', code: 'PH', phoneCode: '63', chineseName: '菲律宾' },
  { name: 'Pakistan', code: 'PK', phoneCode: '92', chineseName: '巴基斯坦' },
  { name: 'Poland', code: 'PL', phoneCode: '48', chineseName: '波兰' },
  {
    name: 'St. Pierre & Miquelon',
    code: 'PM',
    phoneCode: '508',
    chineseName: '圣皮埃尔和密克隆群岛'
  },
  { name: 'Pitcairn Islands', code: 'PN', phoneCode: '872', chineseName: '皮特凯恩群岛' },
  { name: 'Puerto Rico', code: 'PR', phoneCode: '1', chineseName: '波多黎各' },
  { name: 'Palestinian Territories', code: 'PS', phoneCode: '970', chineseName: '巴勒斯坦领土' },
  { name: 'Portugal', code: 'PT', phoneCode: '351', chineseName: '葡萄牙' },
  { name: 'Palau', code: 'PW', phoneCode: '680', chineseName: '帕劳' },
  { name: 'Paraguay', code: 'PY', phoneCode: '595', chineseName: '巴拉圭' },
  { name: 'Qatar', code: 'QA', phoneCode: '974', chineseName: '卡塔尔' },
  { name: 'Réunion', code: 'RE', phoneCode: '262', chineseName: '留尼汪' },
  { name: 'Romania', code: 'RO', phoneCode: '40', chineseName: '罗马尼亚' },
  { name: 'Serbia', code: 'RS', phoneCode: '381', chineseName: '塞尔维亚' },
  { name: 'Russia', code: 'RU', phoneCode: '7', chineseName: '俄罗斯' },
  { name: 'Rwanda', code: 'RW', phoneCode: '250', chineseName: '卢旺达' },
  { name: 'Saudi Arabia', code: 'SA', phoneCode: '966', chineseName: '沙特阿拉伯' },
  { name: 'Solomon Islands', code: 'SB', phoneCode: '677', chineseName: '所罗门群岛' },
  { name: 'Seychelles', code: 'SC', phoneCode: '248', chineseName: '塞舌尔' },
  { name: 'Sudan', code: 'SD', phoneCode: '249', chineseName: '苏丹' },
  { name: 'Sweden', code: 'SE', phoneCode: '46', chineseName: '瑞典' },
  { name: 'Singapore', code: 'SG', phoneCode: '65', chineseName: '新加坡' },
  { name: 'St. Helena', code: 'SH', phoneCode: '290', chineseName: '圣赫勒拿' },
  { name: 'Slovenia', code: 'SI', phoneCode: '386', chineseName: '斯洛文尼亚' },
  { name: 'Svalbard & Jan Mayen', code: 'SJ', phoneCode: '47', chineseName: '斯瓦尔巴特和扬马延' },
  { name: 'Slovakia', code: 'SK', phoneCode: '421', chineseName: '斯洛伐克' },
  { name: 'Sierra Leone', code: 'SL', phoneCode: '232', chineseName: '塞拉利昂' },
  { name: 'San Marino', code: 'SM', phoneCode: '378', chineseName: '圣马力诺' },
  { name: 'Senegal', code: 'SN', phoneCode: '221', chineseName: '塞内加尔' },
  { name: 'Somalia', code: 'SO', phoneCode: '252', chineseName: '索马里' },
  { name: 'Suriname', code: 'SR', phoneCode: '597', chineseName: '苏里南' },
  { name: 'South Sudan', code: 'SS', phoneCode: '211', chineseName: '南苏丹' },
  { name: 'São Tomé & Príncipe', code: 'ST', phoneCode: '239', chineseName: '圣多美和普林西比' },
  { name: 'El Salvador', code: 'SV', phoneCode: '503', chineseName: '萨尔瓦多' },
  { name: 'Sint Maarten', code: 'SX', phoneCode: '599', chineseName: '荷属圣马丁' },
  { name: 'Syria', code: 'SY', phoneCode: '963', chineseName: '叙利亚' },
  { name: 'Swaziland', code: 'SZ', phoneCode: '268', chineseName: '斯威士兰' },
  { name: 'Turks & Caicos Islands', code: 'TC', phoneCode: '1', chineseName: '特克斯和凯科斯群岛' },
  { name: 'Chad', code: 'TD', phoneCode: '235', chineseName: '乍得' },
  {
    name: 'French Southern Territories',
    code: 'TF',
    phoneCode: '(null)',
    chineseName: '法属南部领地'
  },
  { name: 'Togo', code: 'TG', phoneCode: '228', chineseName: '多哥' },
  { name: 'Thailand', code: 'TH', phoneCode: '66', chineseName: '泰国' },
  { name: 'Tajikistan', code: 'TJ', phoneCode: '992', chineseName: '塔吉克斯坦' },
  { name: 'Tokelau', code: 'TK', phoneCode: '690', chineseName: '托克劳' },
  { name: 'Timor-Leste', code: 'TL', phoneCode: '670', chineseName: '东帝汶' },
  { name: 'Turkmenistan', code: 'TM', phoneCode: '993', chineseName: '土库曼斯坦' },
  { name: 'Tunisia', code: 'TN', phoneCode: '216', chineseName: '突尼斯' },
  { name: 'Tonga', code: 'TO', phoneCode: '676', chineseName: '汤加' },
  { name: 'Turkey', code: 'TR', phoneCode: '90', chineseName: '土耳其' },
  { name: 'Trinidad & Tobago', code: 'TT', phoneCode: '1', chineseName: '特立尼达和多巴哥' },
  { name: 'Tuvalu', code: 'TV', phoneCode: '688', chineseName: '图瓦卢' },
  { name: 'Taiwan', code: 'TW', phoneCode: '886', chineseName: '台湾' },
  { name: 'Tanzania', code: 'TZ', phoneCode: '255', chineseName: '坦桑尼亚' },
  { name: 'Ukraine', code: 'UA', phoneCode: '380', chineseName: '乌克兰' },
  { name: 'Uganda', code: 'UG', phoneCode: '256', chineseName: '乌干达' },
  {
    name: 'U.S. Outlying Islands',
    code: 'UM',
    phoneCode: '(null)',
    chineseName: '美国本土外小岛屿'
  },
  { name: 'United States', code: 'US', phoneCode: '1', chineseName: '美国' },
  { name: 'Uruguay', code: 'UY', phoneCode: '598', chineseName: '乌拉圭' },
  { name: 'Uzbekistan', code: 'UZ', phoneCode: '998', chineseName: '乌兹别克斯坦' },
  { name: 'Vatican City', code: 'VA', phoneCode: '379', chineseName: '梵蒂冈' },
  {
    name: 'St. Vincent & Grenadines',
    code: 'VC',
    phoneCode: '1',
    chineseName: '圣文森特和格林纳丁斯'
  },
  { name: 'Venezuela', code: 'VE', phoneCode: '58', chineseName: '委内瑞拉' },
  { name: 'British Virgin Islands', code: 'VG', phoneCode: '1', chineseName: '英属维京群岛' },
  { name: 'U.S. Virgin Islands', code: 'VI', phoneCode: '1', chineseName: '美属维京群岛' },
  { name: 'Vietnam', code: 'VN', phoneCode: '84', chineseName: '越南' },
  { name: 'Vanuatu', code: 'VU', phoneCode: '678', chineseName: '瓦努阿图' },
  { name: 'Wallis & Futuna', code: 'WF', phoneCode: '681', chineseName: '瓦利斯和富图纳' },
  { name: 'Samoa', code: 'WS', phoneCode: '685', chineseName: '萨摩亚' },
  { name: 'Yemen', code: 'YE', phoneCode: '967', chineseName: '也门' },
  { name: 'Mayotte', code: 'YT', phoneCode: '262', chineseName: '马约特' },
  { name: 'South Africa', code: 'ZA', phoneCode: '27', chineseName: '南非' },
  { name: 'Zambia', code: 'ZM', phoneCode: '260', chineseName: '赞比亚' },
  { name: 'Zimbabwe', code: 'ZW', phoneCode: '263', chineseName: '津巴布韦' }
];
